### ISSUE TITLE
Make path prefix synchronization more robust and agnostic to repository name

### ISSUE THREAD

**Issue by ebalogun01** [ebalogun01/EV-EcoSim#92]
Currently, the platform will throw an exception if the repository is re-named arbitrarily by anyone who clones it. This is because path prefix synchronization has been manually hard-coded. A fix is needed to make this os, machine, and repository name agnostic, given the repository structure is not tampered with.

**Comment by Plavit** [comment]
Great job @ebalogun01! Is this solved just via relative paths or some other magic sauce was used as well?
